classDiagram
    %% Classes principales
    class Book {
        int id
        string title
        string author
        date publicationDate
        string ISBN
        int categoryId
        string description
    }

    class Category {
        int id
        string name
    }

    class User {
        int id
        string username
        string email
    }

    %% Relations
    Category "0..*" -- "0..*" Book : has
    User "1" -- "0..*" Book : "created"

